language: python

before_script:
  - wget https://github.com/eddrial/wRadia/archive/0.1.tar.gz -O /tmp/casper.tar.gz
  - tar -xvf /tmp/casper.tar.gz
  - export PATH=$PATH:$PWD/wRadia-0.1/bin/

services:
  - docker

install:
  - docker pull eddrial/opt-id:env-v3
  - docker run -itd --name env --env-file <(env | grep TRAVIS) -v $(pwd):/tmp/repo/ -w /tmp/repo/ eddrial/opt-id:env-v3
  
script:
  - docker exec env pip install -e .
  - docker exec env python -m pytest --cov=idmodels test/

after_script:
  - docker exec env coveralls
  - docker stop env
